spring:
    servlet:
        multipart:
            max-request-size: 100MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: docvalide@gmail.com
        password: xeoswshpfeymumsk
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
                    auth: true

app:
    datasource:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5433/docvalidetest
        maximum-pool-size: 30
        password: docv@lide#1234
        username: ghosttech

files:
    directory: documents

server:
    error:
        include-binding-errors: always
        include-message: always
    port: 8083


sentry:
    dsn: https://6e8deabe5d97489bba3b21c763c23ebd@o450724.ingest.sentry.io/4506366821990400
    tracesSampleRate: 1.0
    exception-resolver-order: -2147483647
    environment: test