app:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5433/docvalide
    maximum-pool-size: 30
    password: password
    username: ghosttech

server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8081

spring:
  mail:
    host: smtp.gmail.com
    username: docvalide@gmail.com
    password: xeoswshpfeymumsk
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

