spring:
  servlet:
    multipart:
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: docvalide@gmail.com
    password: xeoswshpfeymumsk
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

app:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5433/docvalide
    maximum-pool-size: 30
    password: docv@lide#1234
    username: ghosttech

files:
  directory: documents

server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8082
