spring:
    servlet:
        multipart:
            max-request-size: 100MB
    mail:
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
                    auth: true
        host: smtp.gmail.com
        username: docvalide@gmail.com
        password: xeoswshpfeymumsk
        port: 587

app:
    datasource:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5433/docvalidetest
        maximum-pool-size: 30
        password: docv@lide#1234
        username: ghosttech
files:
    directory: documents
server:
    error:
        include-binding-errors: always
        include-message: always
    port: 8081
