app:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5433/docvalide
    maximum-pool-size: 30
    password: password
    username: ghosttech

server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8081

spring:
  mail:
    host: localhost
    username: docvalide@gmail.com
    port: 1025
    properties:
      mail:
        smtp:
          starttls:
            enable: false
            required: false
          auth: false

sentry:
  dsn: https://6e8deabe5d97489bba3b21c763c23ebd@o450724.ingest.sentry.io/4506366821990400
  tracesSampleRate: 1.0
  exception-resolver-order: -2147483647
  environment: local